apiVersion: v1
kind: Pod
metadata:
  name: app-event-simulator
  namespace: efk
  labels:
    name: app
spec:
  containers:
  - name: app
    image: manishgenius/event-simulator:latest
    volumeMounts:
    - mountPath: /log
      name: log-volume

  # Volume to store the logs
  volumes:
  - name: log-volume
    hostPath:
      path: /var/log/webapp
      type: DirectoryOrCreate
